\restrict dbmate

-- Dumped from database version 18.4 (Debian 18.4-1.pgdg13+1)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS '';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: claim_concepts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claim_concepts (
    claim_id bigint NOT NULL,
    concept_id bigint NOT NULL
);


--
-- Name: claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.claims (
    id bigint NOT NULL,
    source_id bigint,
    thinker_id bigint,
    claim_text text NOT NULL,
    claim_type text,
    domain text,
    consumer_implication text,
    signal_strength text,
    specificity integer,
    quote text,
    claim_weight double precision,
    freshness_score double precision,
    duplicate_of bigint,
    has_statistic boolean DEFAULT false,
    statistic text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT claims_signal_strength_check CHECK ((signal_strength = ANY (ARRAY['noise'::text, 'background'::text, 'signal'::text, 'strong_signal'::text]))),
    CONSTRAINT claims_specificity_check CHECK (((specificity >= 1) AND (specificity <= 5)))
);


--
-- Name: claims_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.claims ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.claims_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: concept_thinkers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.concept_thinkers (
    concept_id bigint NOT NULL,
    thinker_id bigint NOT NULL,
    stance text
);


--
-- Name: concepts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.concepts (
    id bigint NOT NULL,
    name text NOT NULL,
    description text,
    consumer_relevance text,
    keynote_relevance text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: concepts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.concepts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.concepts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    key text NOT NULL,
    body jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: domain_flows; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_flows (
    id bigint NOT NULL,
    source_id text NOT NULL,
    target_id text NOT NULL,
    strength text NOT NULL,
    description text
);


--
-- Name: domain_flows_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domain_flows ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_flows_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_key_trends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_key_trends (
    id bigint NOT NULL,
    slug text NOT NULL,
    domain_id text NOT NULL,
    name text NOT NULL,
    subtitle text NOT NULL,
    velocity text,
    hero_stat jsonb,
    sort_order integer NOT NULL,
    proponents text,
    skeptics text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: domain_key_trends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domain_key_trends ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_key_trends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_links (
    id bigint NOT NULL,
    source_type text NOT NULL,
    source_id text NOT NULL,
    target_type text NOT NULL,
    target_id text NOT NULL,
    relationship text NOT NULL,
    strength double precision NOT NULL,
    reasoning text
);


--
-- Name: domain_links_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domain_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_sub_trend_claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_sub_trend_claims (
    sub_trend_id bigint NOT NULL,
    claim_id bigint NOT NULL
);


--
-- Name: domain_sub_trends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_sub_trends (
    id bigint NOT NULL,
    slug text NOT NULL,
    kt_id bigint NOT NULL,
    domain_id text NOT NULL,
    name text NOT NULL,
    subtitle text,
    description text NOT NULL,
    sort_order integer NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: domain_sub_trends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domain_sub_trends ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_sub_trends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domain_synthesis_insight_claims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_synthesis_insight_claims (
    insight_id bigint NOT NULL,
    claim_id bigint NOT NULL
);


--
-- Name: domain_synthesis_insights; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domain_synthesis_insights (
    id bigint NOT NULL,
    slug text NOT NULL,
    domain_id text NOT NULL,
    name text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: domain_synthesis_insights_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.domain_synthesis_insights ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.domain_synthesis_insights_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: domains_v2; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.domains_v2 (
    id text NOT NULL,
    name text NOT NULL,
    label text NOT NULL,
    short_description text NOT NULL,
    description text NOT NULL,
    sort_order integer NOT NULL
);


--
-- Name: predictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.predictions (
    id bigint NOT NULL,
    prediction_id text NOT NULL,
    claim_id bigint,
    thinker_id bigint,
    source_id bigint,
    claim_text text NOT NULL,
    timeframe text,
    domain text,
    specificity integer,
    falsifiable boolean DEFAULT true,
    status text DEFAULT 'pending'::text,
    consensus_alignment double precision,
    evaluation_date date,
    evaluation_notes text,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT predictions_consensus_alignment_check CHECK (((consensus_alignment >= (0.0)::double precision) AND (consensus_alignment <= (1.0)::double precision))),
    CONSTRAINT predictions_specificity_check CHECK (((specificity >= 1) AND (specificity <= 5))),
    CONSTRAINT predictions_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'partially_true'::text, 'true'::text, 'false'::text, 'expired'::text])))
);


--
-- Name: predictions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.predictions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.predictions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: scrape_sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scrape_sources (
    id bigint NOT NULL,
    thinker_id bigint NOT NULL,
    platform text NOT NULL,
    method text NOT NULL,
    url text,
    rss text,
    channel_url text,
    handle text,
    note text
);


--
-- Name: scrape_sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.scrape_sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scrape_sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: source_state; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.source_state (
    id bigint NOT NULL,
    thinker_id bigint NOT NULL,
    platform text NOT NULL,
    source_url text NOT NULL,
    last_fetched_at timestamp with time zone,
    last_item_date date,
    last_run_status text,
    items_last_run integer DEFAULT 0,
    CONSTRAINT source_state_last_run_status_check CHECK ((last_run_status = ANY (ARRAY['ok'::text, 'partial'::text, 'failed'::text])))
);


--
-- Name: source_state_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.source_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.source_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sources (
    id bigint NOT NULL,
    thinker_id bigint,
    title text NOT NULL,
    date_published date,
    source_type text,
    platform text,
    url text,
    summary text,
    full_text text,
    consumer_implication text,
    signal_strength text,
    novelty text,
    keynote_impact text,
    confidence text,
    filename text,
    source_depth integer,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT sources_signal_strength_check CHECK ((signal_strength = ANY (ARRAY['noise'::text, 'background'::text, 'signal'::text, 'strong_signal'::text])))
);


--
-- Name: sources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tensions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tensions (
    id bigint NOT NULL,
    name text NOT NULL,
    description text,
    side_a text,
    side_b text,
    consumer_implications text,
    current_balance text,
    keynote_relevance text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


--
-- Name: tensions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tensions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tensions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: thinker_disagreements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.thinker_disagreements (
    thinker_a_id bigint NOT NULL,
    thinker_b_id bigint NOT NULL,
    topic text NOT NULL,
    description text
);


--
-- Name: thinkers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.thinkers (
    id bigint NOT NULL,
    name text NOT NULL,
    affiliation text,
    domain text,
    agi_timeline text,
    economic_worldview text,
    consumer_behavior_stance text,
    importance_score integer,
    signal_quality text,
    credibility_score double precision DEFAULT 50.0,
    prediction_accuracy double precision,
    outlier_factor double precision,
    bio text,
    image_url text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT thinkers_importance_score_check CHECK (((importance_score >= 1) AND (importance_score <= 10)))
);


--
-- Name: thinkers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.thinkers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thinkers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: claim_concepts claim_concepts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_concepts
    ADD CONSTRAINT claim_concepts_pkey PRIMARY KEY (claim_id, concept_id);


--
-- Name: claims claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_pkey PRIMARY KEY (id);


--
-- Name: concept_thinkers concept_thinkers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_thinkers
    ADD CONSTRAINT concept_thinkers_pkey PRIMARY KEY (concept_id, thinker_id);


--
-- Name: concepts concepts_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_name_key UNIQUE (name);


--
-- Name: concepts concepts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concepts
    ADD CONSTRAINT concepts_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (key);


--
-- Name: domain_flows domain_flows_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_flows
    ADD CONSTRAINT domain_flows_pkey PRIMARY KEY (id);


--
-- Name: domain_flows domain_flows_source_id_target_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_flows
    ADD CONSTRAINT domain_flows_source_id_target_id_key UNIQUE (source_id, target_id);


--
-- Name: domain_key_trends domain_key_trends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_key_trends
    ADD CONSTRAINT domain_key_trends_pkey PRIMARY KEY (id);


--
-- Name: domain_key_trends domain_key_trends_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_key_trends
    ADD CONSTRAINT domain_key_trends_slug_key UNIQUE (slug);


--
-- Name: domain_links domain_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_links
    ADD CONSTRAINT domain_links_pkey PRIMARY KEY (id);


--
-- Name: domain_links domain_links_source_type_source_id_target_type_target_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_links
    ADD CONSTRAINT domain_links_source_type_source_id_target_type_target_id_key UNIQUE (source_type, source_id, target_type, target_id);


--
-- Name: domain_sub_trend_claims domain_sub_trend_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trend_claims
    ADD CONSTRAINT domain_sub_trend_claims_pkey PRIMARY KEY (sub_trend_id, claim_id);


--
-- Name: domain_sub_trends domain_sub_trends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trends
    ADD CONSTRAINT domain_sub_trends_pkey PRIMARY KEY (id);


--
-- Name: domain_sub_trends domain_sub_trends_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trends
    ADD CONSTRAINT domain_sub_trends_slug_key UNIQUE (slug);


--
-- Name: domain_synthesis_insight_claims domain_synthesis_insight_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insight_claims
    ADD CONSTRAINT domain_synthesis_insight_claims_pkey PRIMARY KEY (insight_id, claim_id);


--
-- Name: domain_synthesis_insights domain_synthesis_insights_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insights
    ADD CONSTRAINT domain_synthesis_insights_pkey PRIMARY KEY (id);


--
-- Name: domain_synthesis_insights domain_synthesis_insights_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insights
    ADD CONSTRAINT domain_synthesis_insights_slug_key UNIQUE (slug);


--
-- Name: domains_v2 domains_v2_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domains_v2
    ADD CONSTRAINT domains_v2_pkey PRIMARY KEY (id);


--
-- Name: predictions predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_pkey PRIMARY KEY (id);


--
-- Name: predictions predictions_prediction_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_prediction_id_key UNIQUE (prediction_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: scrape_sources scrape_sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_sources
    ADD CONSTRAINT scrape_sources_pkey PRIMARY KEY (id);


--
-- Name: source_state source_state_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_state
    ADD CONSTRAINT source_state_pkey PRIMARY KEY (id);


--
-- Name: source_state source_state_thinker_id_platform_source_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_state
    ADD CONSTRAINT source_state_thinker_id_platform_source_url_key UNIQUE (thinker_id, platform, source_url);


--
-- Name: sources sources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_pkey PRIMARY KEY (id);


--
-- Name: tensions tensions_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tensions
    ADD CONSTRAINT tensions_name_key UNIQUE (name);


--
-- Name: tensions tensions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tensions
    ADD CONSTRAINT tensions_pkey PRIMARY KEY (id);


--
-- Name: thinker_disagreements thinker_disagreements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thinker_disagreements
    ADD CONSTRAINT thinker_disagreements_pkey PRIMARY KEY (thinker_a_id, thinker_b_id, topic);


--
-- Name: thinkers thinkers_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thinkers
    ADD CONSTRAINT thinkers_name_key UNIQUE (name);


--
-- Name: thinkers thinkers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thinkers
    ADD CONSTRAINT thinkers_pkey PRIMARY KEY (id);


--
-- Name: idx_claims_domain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_domain ON public.claims USING btree (domain);


--
-- Name: idx_claims_duplicate_of; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_duplicate_of ON public.claims USING btree (duplicate_of);


--
-- Name: idx_claims_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_source ON public.claims USING btree (source_id);


--
-- Name: idx_claims_strength; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_strength ON public.claims USING btree (signal_strength);


--
-- Name: idx_claims_thinker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_thinker ON public.claims USING btree (thinker_id);


--
-- Name: idx_claims_weight; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_claims_weight ON public.claims USING btree (claim_weight DESC NULLS LAST);


--
-- Name: idx_dkt_domain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dkt_domain ON public.domain_key_trends USING btree (domain_id);


--
-- Name: idx_dst_kt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dst_kt ON public.domain_sub_trends USING btree (kt_id);


--
-- Name: idx_predictions_domain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_predictions_domain ON public.predictions USING btree (domain);


--
-- Name: idx_predictions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_predictions_status ON public.predictions USING btree (status);


--
-- Name: idx_predictions_thinker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_predictions_thinker ON public.predictions USING btree (thinker_id);


--
-- Name: idx_scrape_sources_thinker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_scrape_sources_thinker ON public.scrape_sources USING btree (thinker_id);


--
-- Name: idx_sources_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sources_date ON public.sources USING btree (date_published);


--
-- Name: idx_sources_thinker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sources_thinker ON public.sources USING btree (thinker_id);


--
-- Name: claim_concepts claim_concepts_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_concepts
    ADD CONSTRAINT claim_concepts_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id);


--
-- Name: claim_concepts claim_concepts_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claim_concepts
    ADD CONSTRAINT claim_concepts_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id);


--
-- Name: claims claims_duplicate_of_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_duplicate_of_fkey FOREIGN KEY (duplicate_of) REFERENCES public.claims(id);


--
-- Name: claims claims_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id);


--
-- Name: claims claims_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.claims
    ADD CONSTRAINT claims_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: concept_thinkers concept_thinkers_concept_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_thinkers
    ADD CONSTRAINT concept_thinkers_concept_id_fkey FOREIGN KEY (concept_id) REFERENCES public.concepts(id);


--
-- Name: concept_thinkers concept_thinkers_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.concept_thinkers
    ADD CONSTRAINT concept_thinkers_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: domain_flows domain_flows_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_flows
    ADD CONSTRAINT domain_flows_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.domains_v2(id);


--
-- Name: domain_flows domain_flows_target_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_flows
    ADD CONSTRAINT domain_flows_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.domains_v2(id);


--
-- Name: domain_key_trends domain_key_trends_domain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_key_trends
    ADD CONSTRAINT domain_key_trends_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES public.domains_v2(id);


--
-- Name: domain_sub_trend_claims domain_sub_trend_claims_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trend_claims
    ADD CONSTRAINT domain_sub_trend_claims_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id);


--
-- Name: domain_sub_trend_claims domain_sub_trend_claims_sub_trend_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trend_claims
    ADD CONSTRAINT domain_sub_trend_claims_sub_trend_id_fkey FOREIGN KEY (sub_trend_id) REFERENCES public.domain_sub_trends(id);


--
-- Name: domain_sub_trends domain_sub_trends_domain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trends
    ADD CONSTRAINT domain_sub_trends_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES public.domains_v2(id);


--
-- Name: domain_sub_trends domain_sub_trends_kt_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_sub_trends
    ADD CONSTRAINT domain_sub_trends_kt_id_fkey FOREIGN KEY (kt_id) REFERENCES public.domain_key_trends(id);


--
-- Name: domain_synthesis_insight_claims domain_synthesis_insight_claims_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insight_claims
    ADD CONSTRAINT domain_synthesis_insight_claims_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id);


--
-- Name: domain_synthesis_insight_claims domain_synthesis_insight_claims_insight_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insight_claims
    ADD CONSTRAINT domain_synthesis_insight_claims_insight_id_fkey FOREIGN KEY (insight_id) REFERENCES public.domain_synthesis_insights(id);


--
-- Name: domain_synthesis_insights domain_synthesis_insights_domain_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.domain_synthesis_insights
    ADD CONSTRAINT domain_synthesis_insights_domain_id_fkey FOREIGN KEY (domain_id) REFERENCES public.domains_v2(id);


--
-- Name: predictions predictions_claim_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.claims(id);


--
-- Name: predictions predictions_source_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_source_id_fkey FOREIGN KEY (source_id) REFERENCES public.sources(id);


--
-- Name: predictions predictions_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: scrape_sources scrape_sources_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scrape_sources
    ADD CONSTRAINT scrape_sources_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: source_state source_state_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.source_state
    ADD CONSTRAINT source_state_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: sources sources_thinker_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sources
    ADD CONSTRAINT sources_thinker_id_fkey FOREIGN KEY (thinker_id) REFERENCES public.thinkers(id);


--
-- Name: thinker_disagreements thinker_disagreements_thinker_a_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thinker_disagreements
    ADD CONSTRAINT thinker_disagreements_thinker_a_id_fkey FOREIGN KEY (thinker_a_id) REFERENCES public.thinkers(id);


--
-- Name: thinker_disagreements thinker_disagreements_thinker_b_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.thinker_disagreements
    ADD CONSTRAINT thinker_disagreements_thinker_b_id_fkey FOREIGN KEY (thinker_b_id) REFERENCES public.thinkers(id);


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('0001'),
    ('0002');
