-- migrate:up
-- =============================================================================
-- Serious Shift — schema (clean, minimal, scalable).
--
-- Only the tables the running code actually uses are defined here. The legacy
-- v1 trend-map (macro_scenarios / sub_trends / …), the scenario layer, tagging,
-- and the old keynote_sections tables were removed — the current pipeline writes
-- the domain-first v2 map and serves documents as JSON blobs.
--
-- Conventions:
--   * BIGINT GENERATED BY DEFAULT AS IDENTITY — "BY DEFAULT" still allows an
--     explicit id (so the optional one-off ETL can preserve ids).
--   * Open-ended classifier columns (domain, claim_type, source_type, …) are
--     plain TEXT so new values never require a migration. CHECK constraints are
--     kept only where the code depends on the exact set (signal_strength,
--     prediction.status, *_score ranges).
--   * Whole-document JSON (map / keynote / synthesis / daily) lives in `documents`.
-- =============================================================================

-- ── Core entities ────────────────────────────────────────────────────────────

CREATE TABLE thinkers (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                     TEXT UNIQUE NOT NULL,
    affiliation              TEXT,
    domain                   TEXT,
    agi_timeline             TEXT,
    economic_worldview       TEXT,
    consumer_behavior_stance TEXT,
    importance_score         INTEGER CHECK (importance_score BETWEEN 1 AND 10),
    signal_quality           TEXT,
    credibility_score        DOUBLE PRECISION DEFAULT 50.0,
    prediction_accuracy      DOUBLE PRECISION,
    outlier_factor           DOUBLE PRECISION,
    bio                      TEXT,
    image_url                TEXT,
    created_at               TIMESTAMPTZ DEFAULT now(),
    updated_at               TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE sources (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_id           BIGINT REFERENCES thinkers(id),
    title                TEXT NOT NULL,
    date_published       DATE,
    source_type          TEXT,
    platform             TEXT,
    url                  TEXT,
    summary              TEXT,
    full_text            TEXT,
    consumer_implication TEXT,
    signal_strength      TEXT CHECK (signal_strength IN ('noise','background','signal','strong_signal')),
    novelty              TEXT,
    keynote_impact       TEXT,
    confidence           TEXT,
    filename             TEXT,
    source_depth         INTEGER,
    created_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE claims (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id            BIGINT REFERENCES sources(id),
    thinker_id           BIGINT REFERENCES thinkers(id),
    claim_text           TEXT NOT NULL,
    claim_type           TEXT,
    domain               TEXT,
    consumer_implication TEXT,
    signal_strength      TEXT CHECK (signal_strength IN ('noise','background','signal','strong_signal')),
    specificity          INTEGER CHECK (specificity BETWEEN 1 AND 5),
    quote                TEXT,
    claim_weight         DOUBLE PRECISION,
    freshness_score      DOUBLE PRECISION,
    duplicate_of         BIGINT REFERENCES claims(id),
    has_statistic        BOOLEAN DEFAULT FALSE,
    statistic            TEXT,
    created_at           TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE predictions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prediction_id       TEXT UNIQUE NOT NULL,
    claim_id            BIGINT REFERENCES claims(id),
    thinker_id          BIGINT REFERENCES thinkers(id),
    source_id           BIGINT REFERENCES sources(id),
    claim_text          TEXT NOT NULL,
    timeframe           TEXT,
    domain              TEXT,
    specificity         INTEGER CHECK (specificity BETWEEN 1 AND 5),
    falsifiable         BOOLEAN DEFAULT TRUE,
    status              TEXT CHECK (status IN ('pending','partially_true','true','false','expired')) DEFAULT 'pending',
    consensus_alignment DOUBLE PRECISION CHECK (consensus_alignment BETWEEN 0.0 AND 1.0),
    evaluation_date     DATE,
    evaluation_notes    TEXT,
    created_at          TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE concepts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               TEXT UNIQUE NOT NULL,
    description        TEXT,
    consumer_relevance TEXT,
    keynote_relevance  TEXT,
    created_at         TIMESTAMPTZ DEFAULT now(),
    updated_at         TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE tensions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  TEXT UNIQUE NOT NULL,
    description           TEXT,
    side_a                TEXT,
    side_b                TEXT,
    consumer_implications TEXT,
    current_balance       TEXT,
    keynote_relevance     TEXT,
    created_at            TIMESTAMPTZ DEFAULT now(),
    updated_at            TIMESTAMPTZ DEFAULT now()
);

-- ── Junctions over core entities ─────────────────────────────────────────────

CREATE TABLE claim_concepts (
    claim_id   BIGINT REFERENCES claims(id),
    concept_id BIGINT REFERENCES concepts(id),
    PRIMARY KEY (claim_id, concept_id)
);

CREATE TABLE concept_thinkers (
    concept_id BIGINT REFERENCES concepts(id),
    thinker_id BIGINT REFERENCES thinkers(id),
    stance     TEXT,
    PRIMARY KEY (concept_id, thinker_id)
);

CREATE TABLE thinker_disagreements (
    thinker_a_id BIGINT REFERENCES thinkers(id),
    thinker_b_id BIGINT REFERENCES thinkers(id),
    topic        TEXT,
    description  TEXT,
    PRIMARY KEY (thinker_a_id, thinker_b_id, topic)
);

-- ── Scraper: source manifest (what to fetch) + watermark state ────────────────

CREATE TABLE scrape_sources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_id  BIGINT NOT NULL REFERENCES thinkers(id),
    platform    TEXT NOT NULL,
    method      TEXT NOT NULL,
    url         TEXT,
    rss         TEXT,
    channel_url TEXT,
    handle      TEXT,
    note        TEXT
);

CREATE TABLE source_state (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_id      BIGINT NOT NULL REFERENCES thinkers(id),
    platform        TEXT NOT NULL,
    source_url      TEXT NOT NULL,
    last_fetched_at TIMESTAMPTZ,
    last_item_date  DATE,
    last_run_status TEXT CHECK (last_run_status IN ('ok','partial','failed')),
    items_last_run  INTEGER DEFAULT 0,
    UNIQUE (thinker_id, platform, source_url)
);

-- ── Served documents (assembled JSON blobs) ───────────────────────────────────

CREATE TABLE documents (
    key        TEXT PRIMARY KEY,        -- 'map' | 'keynote' | 'synthesis' | 'daily'
    body       JSONB NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ── Domain-first trend map (domain → key trend → sub-trend → claim) ────────────

CREATE TABLE domains_v2 (
    id                TEXT PRIMARY KEY,
    name              TEXT NOT NULL,
    label             TEXT NOT NULL,
    short_description TEXT NOT NULL,
    description       TEXT NOT NULL,
    sort_order        INTEGER NOT NULL
);

CREATE TABLE domain_key_trends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    subtitle    TEXT NOT NULL,
    velocity    TEXT,
    hero_stat   JSONB,
    sort_order  INTEGER NOT NULL,
    proponents  TEXT,
    skeptics    TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_sub_trends (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    kt_id       BIGINT NOT NULL REFERENCES domain_key_trends(id),
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    subtitle    TEXT,
    description TEXT NOT NULL,
    sort_order  INTEGER NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_sub_trend_claims (
    sub_trend_id BIGINT REFERENCES domain_sub_trends(id),
    claim_id     BIGINT REFERENCES claims(id),
    PRIMARY KEY (sub_trend_id, claim_id)
);

CREATE TABLE domain_synthesis_insights (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug        TEXT UNIQUE NOT NULL,
    domain_id   TEXT NOT NULL REFERENCES domains_v2(id),
    name        TEXT NOT NULL,
    description TEXT NOT NULL,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE domain_synthesis_insight_claims (
    insight_id BIGINT REFERENCES domain_synthesis_insights(id),
    claim_id   BIGINT REFERENCES claims(id),
    PRIMARY KEY (insight_id, claim_id)
);

CREATE TABLE domain_links (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type  TEXT NOT NULL,
    source_id    TEXT NOT NULL,
    target_type  TEXT NOT NULL,
    target_id    TEXT NOT NULL,
    relationship TEXT NOT NULL,
    strength     DOUBLE PRECISION NOT NULL,
    reasoning    TEXT,
    UNIQUE (source_type, source_id, target_type, target_id)
);

CREATE TABLE domain_flows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id   TEXT NOT NULL REFERENCES domains_v2(id),
    target_id   TEXT NOT NULL REFERENCES domains_v2(id),
    strength    TEXT NOT NULL,
    description TEXT,
    UNIQUE (source_id, target_id)
);

-- ── Indexes (hot read paths) ───────────────────────────────────────────────────

CREATE INDEX idx_sources_thinker        ON sources(thinker_id);
CREATE INDEX idx_sources_date           ON sources(date_published);
CREATE INDEX idx_claims_source          ON claims(source_id);
CREATE INDEX idx_claims_thinker         ON claims(thinker_id);
CREATE INDEX idx_claims_domain          ON claims(domain);
CREATE INDEX idx_claims_strength        ON claims(signal_strength);
CREATE INDEX idx_claims_duplicate_of    ON claims(duplicate_of);
CREATE INDEX idx_claims_weight          ON claims(claim_weight DESC NULLS LAST);
CREATE INDEX idx_predictions_thinker    ON predictions(thinker_id);
CREATE INDEX idx_predictions_status     ON predictions(status);
CREATE INDEX idx_predictions_domain     ON predictions(domain);
CREATE INDEX idx_scrape_sources_thinker ON scrape_sources(thinker_id);
CREATE INDEX idx_dkt_domain             ON domain_key_trends(domain_id);
CREATE INDEX idx_dst_kt                 ON domain_sub_trends(kt_id);

-- migrate:down
DROP TABLE IF EXISTS domain_flows;
DROP TABLE IF EXISTS domain_links;
DROP TABLE IF EXISTS domain_synthesis_insight_claims;
DROP TABLE IF EXISTS domain_synthesis_insights;
DROP TABLE IF EXISTS domain_sub_trend_claims;
DROP TABLE IF EXISTS domain_sub_trends;
DROP TABLE IF EXISTS domain_key_trends;
DROP TABLE IF EXISTS domains_v2;
DROP TABLE IF EXISTS documents;
DROP TABLE IF EXISTS source_state;
DROP TABLE IF EXISTS scrape_sources;
DROP TABLE IF EXISTS thinker_disagreements;
DROP TABLE IF EXISTS concept_thinkers;
DROP TABLE IF EXISTS claim_concepts;
DROP TABLE IF EXISTS tensions;
DROP TABLE IF EXISTS concepts;
DROP TABLE IF EXISTS predictions;
DROP TABLE IF EXISTS claims;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS thinkers;
