-- migrate:up
-- =============================================================================
-- 0004 — Generalize thinkers → entities; add research-paper / venue metadata to
-- sources; add a curated reputable-venues table; seed research-paper feeds
-- (arXiv / OpenAlex) and AI lab / org blogs.
--
-- Rationale: the pipeline was thinker-only (every source/claim chained to one of
-- the 69 roster people). This migration lets content attach to ANY entity —
-- person, org, lab, publication, or venue — so we can ingest papers and lab
-- posts and auto-create lightweight entities for newly discovered reputable
-- authors/orgs. All additions are additive/nullable so existing rows are valid.
-- =============================================================================

-- ── Entities: a "thinker" row can now represent a person OR an institution ────
ALTER TABLE thinkers ADD COLUMN entity_kind     TEXT NOT NULL DEFAULT 'person';  -- person|org|lab|publication|venue
ALTER TABLE thinkers ADD COLUMN reputation_tier INTEGER CHECK (reputation_tier BETWEEN 1 AND 5);  -- editor override
ALTER TABLE thinkers ADD COLUMN authority_score DOUBLE PRECISION;                -- 0..1, computed from signals
ALTER TABLE thinkers ADD COLUMN external_ids    JSONB;                           -- {openalex, semantic_scholar, orcid, arxiv}
ALTER TABLE thinkers ADD COLUMN discovered      BOOLEAN NOT NULL DEFAULT FALSE;  -- auto-created via discovery vs curated roster

-- ── Sources: research-paper / venue metadata ─────────────────────────────────
ALTER TABLE sources ADD COLUMN doi            TEXT;
ALTER TABLE sources ADD COLUMN venue          TEXT;            -- journal / conference / lab / publication name
ALTER TABLE sources ADD COLUMN external_id    TEXT;            -- arXiv id / OpenAlex work id
ALTER TABLE sources ADD COLUMN citation_count INTEGER;
ALTER TABLE sources ADD COLUMN peer_reviewed  BOOLEAN;
ALTER TABLE sources ADD COLUMN authors        JSONB;           -- full author list (primary author still → thinker_id)
ALTER TABLE sources ADD COLUMN authority      DOUBLE PRECISION;-- 0..1 reputability of THIS source

-- ── Scrape manifest: JSON params for API-driven feeds (arXiv/OpenAlex) ────────
ALTER TABLE scrape_sources ADD COLUMN params JSONB;

-- ── Curated half of the hybrid reputability gate ─────────────────────────────
CREATE TABLE reputable_venues (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    kind TEXT,                                    -- journal|conference|preprint|lab|org|press
    tier INTEGER NOT NULL CHECK (tier BETWEEN 1 AND 5)  -- 1 = most reputable
);

CREATE INDEX idx_thinkers_entity_kind ON thinkers(entity_kind);
CREATE INDEX idx_sources_doi          ON sources(doi);
CREATE INDEX idx_sources_external_id  ON sources(external_id);

-- ── Seed: reputable venues (tier 1 = top) ────────────────────────────────────
INSERT INTO reputable_venues (name, kind, tier) VALUES
  ('NeurIPS','conference',1), ('ICML','conference',1), ('ICLR','conference',1),
  ('ACL','conference',1), ('EMNLP','conference',2), ('CVPR','conference',1), ('AAAI','conference',2),
  ('Nature','journal',1), ('Science','journal',1), ('PNAS','journal',1),
  ('Nature Machine Intelligence','journal',1),
  ('Quarterly Journal of Economics','journal',1), ('American Economic Review','journal',1),
  ('Journal of Economic Perspectives','journal',2), ('Econometrica','journal',1),
  ('arXiv','preprint',3), ('SSRN','preprint',3), ('NBER','preprint',2),
  ('OpenAI','lab',1), ('Anthropic','lab',1), ('Google DeepMind','lab',1),
  ('Google Research','lab',1), ('Microsoft Research','lab',1),
  ('Hugging Face','org',2), ('Stanford HAI','org',1), ('Stanford SAIL','org',1),
  ('Epoch AI','org',1)
ON CONFLICT (name) DO NOTHING;

-- ── Seed: AI lab / org blog entities + their feeds ────────────────────────────
-- Reuse the existing scraper via method='org_blog' (RSS path) where a feed
-- exists, and method='scrape_index' where it doesn't (Anthropic, DeepMind).
INSERT INTO thinkers (name, entity_kind, reputation_tier, affiliation) VALUES
  ('OpenAI',            'lab', 1, 'OpenAI'),
  ('Anthropic',         'lab', 1, 'Anthropic'),
  ('Google DeepMind',   'lab', 1, 'Google DeepMind'),
  ('Google Research',   'lab', 1, 'Google'),
  ('Microsoft Research','lab', 1, 'Microsoft'),
  ('Hugging Face',      'org', 2, 'Hugging Face'),
  ('Stanford HAI',      'org', 1, 'Stanford University'),
  ('Stanford SAIL',     'org', 1, 'Stanford University'),
  ('Epoch AI',          'org', 1, 'Epoch AI')
ON CONFLICT (name) DO NOTHING;

INSERT INTO scrape_sources (thinker_id, platform, method, url, rss, note)
SELECT id, 'lab_blog', 'org_blog', 'https://openai.com/news', 'https://openai.com/news/rss.xml', 'OpenAI news/research feed'
FROM thinkers WHERE name = 'OpenAI'
UNION ALL
SELECT id, 'lab_blog', 'scrape_index', 'https://www.anthropic.com/news', NULL, 'Anthropic news — no public RSS; index scrape'
FROM thinkers WHERE name = 'Anthropic'
UNION ALL
SELECT id, 'lab_blog', 'scrape_index', 'https://deepmind.google/discover/blog', NULL, 'DeepMind blog — no public RSS; index scrape'
FROM thinkers WHERE name = 'Google DeepMind'
UNION ALL
SELECT id, 'lab_blog', 'org_blog', 'https://research.google/blog/', 'https://research.google/blog/rss/', 'Google Research blog'
FROM thinkers WHERE name = 'Google Research'
UNION ALL
SELECT id, 'lab_blog', 'org_blog', 'https://www.microsoft.com/en-us/research/blog/', 'https://www.microsoft.com/en-us/research/feed/', 'Microsoft Research blog'
FROM thinkers WHERE name = 'Microsoft Research'
UNION ALL
SELECT id, 'lab_blog', 'org_blog', 'https://huggingface.co/blog', 'https://huggingface.co/blog/feed.xml', 'Hugging Face blog'
FROM thinkers WHERE name = 'Hugging Face'
UNION ALL
SELECT id, 'lab_blog', 'org_blog', 'https://hai.stanford.edu/news', 'https://hai.stanford.edu/rss.xml', 'Stanford HAI'
FROM thinkers WHERE name = 'Stanford HAI'
UNION ALL
SELECT id, 'lab_blog', 'org_blog', 'https://ai.stanford.edu/blog/', 'https://ai.stanford.edu/blog/feed.xml', 'Stanford SAIL blog'
FROM thinkers WHERE name = 'Stanford SAIL'
UNION ALL
SELECT id, 'lab_blog', 'scrape_index', 'https://epoch.ai/blog', NULL, 'Epoch AI — index scrape'
FROM thinkers WHERE name = 'Epoch AI';

-- ── Seed: research-paper feeds (arXiv categories + OpenAlex topic queries) ─────
-- These attach to venue entities; process_raw re-attributes each paper's claims
-- to its primary author (auto-creating that entity) via the extraction step.
INSERT INTO thinkers (name, entity_kind, reputation_tier, affiliation) VALUES
  ('arXiv',    'venue', 3, 'Cornell University'),
  ('OpenAlex', 'venue', 3, 'OurResearch')
ON CONFLICT (name) DO NOTHING;

INSERT INTO scrape_sources (thinker_id, platform, method, url, params, note)
SELECT id, 'paper', 'arxiv_category', 'http://export.arxiv.org/api/query',
       '{"categories": ["cs.AI","cs.CL","cs.LG","cs.CY"], "max_results": 60}'::jsonb,
       'arXiv AI categories (title+abstract)'
FROM thinkers WHERE name = 'arXiv'
UNION ALL
SELECT id, 'paper', 'arxiv_category', 'http://export.arxiv.org/api/query',
       '{"categories": ["econ.GN"], "max_results": 40}'::jsonb,
       'arXiv economics (general)'
FROM thinkers WHERE name = 'arXiv'
UNION ALL
SELECT id, 'paper', 'openalex_query', 'https://api.openalex.org/works',
       '{"search": "artificial intelligence economy labor consumers", "min_citations": 5, "per_page": 50}'::jsonb,
       'OpenAlex AI-economics discovery (citation-gated)'
FROM thinkers WHERE name = 'OpenAlex';

-- migrate:down
DELETE FROM scrape_sources WHERE method IN ('arxiv_category','arxiv_author','openalex_query','org_blog');
DELETE FROM thinkers WHERE name IN (
  'OpenAI','Anthropic','Google DeepMind','Google Research','Microsoft Research',
  'Hugging Face','Stanford HAI','Stanford SAIL','Epoch AI','arXiv','OpenAlex'
) AND entity_kind <> 'person';
DROP TABLE IF EXISTS reputable_venues;
DROP INDEX IF EXISTS idx_sources_external_id;
DROP INDEX IF EXISTS idx_sources_doi;
DROP INDEX IF EXISTS idx_thinkers_entity_kind;
ALTER TABLE scrape_sources DROP COLUMN IF EXISTS params;
ALTER TABLE sources DROP COLUMN IF EXISTS authority;
ALTER TABLE sources DROP COLUMN IF EXISTS authors;
ALTER TABLE sources DROP COLUMN IF EXISTS peer_reviewed;
ALTER TABLE sources DROP COLUMN IF EXISTS citation_count;
ALTER TABLE sources DROP COLUMN IF EXISTS external_id;
ALTER TABLE sources DROP COLUMN IF EXISTS venue;
ALTER TABLE sources DROP COLUMN IF EXISTS doi;
ALTER TABLE thinkers DROP COLUMN IF EXISTS discovered;
ALTER TABLE thinkers DROP COLUMN IF EXISTS external_ids;
ALTER TABLE thinkers DROP COLUMN IF EXISTS authority_score;
ALTER TABLE thinkers DROP COLUMN IF EXISTS reputation_tier;
ALTER TABLE thinkers DROP COLUMN IF EXISTS entity_kind;
