-- migrate:up
-- =============================================================================
-- 0006 — Innovations ingested from the Innovation database.
--
-- The upstream Innovation database (tw-the-engine) POSTs generated innovations
-- to the backend (`POST /api/innovations/ingest`). Each payload is one
-- innovation: a few first-class scalar columns (the ones we query/join on) plus
-- the variable-shape nested structures (source_urls, brands, tags, cover_image)
-- kept as JSONB — same convention the `documents` table uses for blobs.
--
-- `source_innovation_id` is the upstream primary key; it's UNIQUE so re-POSTing
-- the same innovation upserts instead of duplicating (idempotent ingest).
-- =============================================================================

CREATE TABLE innovations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_innovation_id BIGINT UNIQUE,               -- upstream Innovation-DB id
    article_url          TEXT,
    source_urls          JSONB NOT NULL DEFAULT '[]'::jsonb,
    title                TEXT,
    body                 TEXT,
    trendbite            TEXT,
    brands               JSONB NOT NULL DEFAULT '[]'::jsonb,
    tags                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    cover_image          JSONB,
    created_at           TIMESTAMPTZ DEFAULT now(),
    updated_at           TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_innovations_source_id ON innovations(source_innovation_id);
CREATE INDEX idx_innovations_created   ON innovations(created_at DESC);

-- migrate:down
DROP TABLE IF EXISTS innovations;
