-- migrate:up
-- =============================================================================
-- 0008 — Drop the tables nothing reads or writes.
--
-- The site serves a single document (/api/map). These five tables were built for
-- an earlier concept-graph idea, are empty in every environment, and had no
-- producer in the pipeline — the only readers were four API endpoints that the
-- front end never called. Those endpoints go with them (see apps/backend).
--
-- Deliberately KEPT:
--   innovations — empty, but POST /api/innovations/ingest is a live integration
--                 point for the upstream Innovation database. Dropping it would
--                 break that producer, so it stays until that feed is retired.
--   predictions — unused by the UI, but the `evaluate` step derives thinker
--                 credibility from prediction outcomes, and credibility ranks
--                 the hero statistic on every shift. Load-bearing.
-- =============================================================================

DROP TABLE IF EXISTS claim_concepts;
DROP TABLE IF EXISTS concept_thinkers;
DROP TABLE IF EXISTS thinker_disagreements;
DROP TABLE IF EXISTS tensions;
DROP TABLE IF EXISTS concepts;

-- migrate:down

CREATE TABLE concepts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE claim_concepts (
    claim_id   BIGINT REFERENCES claims(id),
    concept_id BIGINT REFERENCES concepts(id),
    PRIMARY KEY (claim_id, concept_id)
);

CREATE TABLE concept_thinkers (
    concept_id BIGINT REFERENCES concepts(id),
    thinker_id BIGINT REFERENCES thinkers(id),
    PRIMARY KEY (concept_id, thinker_id)
);

CREATE TABLE tensions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE thinker_disagreements (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    thinker_a_id BIGINT REFERENCES thinkers(id),
    thinker_b_id BIGINT REFERENCES thinkers(id),
    topic        TEXT,
    created_at   TIMESTAMPTZ DEFAULT now()
);
