-- migrate:up

-- Pipeline run history and errors.
--
-- These were JSONL files under ./logs on the container filesystem. The weekly
-- job runs on Railway, where that filesystem dies with the container — so the
-- moment a run failed, the detail needed to diagnose it was gone, and the only
-- surviving signal was an alert saying something had gone wrong. Postgres is
-- already the one piece of durable shared state; put them there.
--
-- Also the join point for the split stages: `ingest` and `synthesize` are now
-- separately triggerable, and `stage` is what distinguishes their runs.

CREATE TABLE public.pipeline_runs (
    id bigint NOT NULL,
    run_id text NOT NULL,
    stage text NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    finished_at timestamp with time zone,
    status text DEFAULT 'running' NOT NULL,
    -- Claim counts bracket the run, so "did this week add anything?" is a column
    -- rather than a re-derivation.
    claims_before integer,
    claims_after integer,
    files_processed integer DEFAULT 0 NOT NULL,
    api_calls integer DEFAULT 0 NOT NULL,
    input_tokens bigint DEFAULT 0 NOT NULL,
    output_tokens bigint DEFAULT 0 NOT NULL,
    cost_usd numeric(12,6) DEFAULT 0 NOT NULL,
    -- Per-step outcomes and anything stage-specific; deliberately schemaless so
    -- adding a step does not need a migration.
    detail jsonb,
    CONSTRAINT pipeline_runs_stage_check
        CHECK ((stage = ANY (ARRAY['ingest'::text, 'synthesize'::text, 'full'::text]))),
    CONSTRAINT pipeline_runs_status_check
        CHECK ((status = ANY (ARRAY['running'::text, 'ok'::text, 'failed'::text, 'aborted'::text])))
);

ALTER TABLE public.pipeline_runs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_runs_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.pipeline_runs ADD CONSTRAINT pipeline_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.pipeline_runs ADD CONSTRAINT pipeline_runs_run_id_key UNIQUE (run_id);

CREATE INDEX idx_pipeline_runs_started ON public.pipeline_runs USING btree (started_at DESC);
CREATE INDEX idx_pipeline_runs_stage ON public.pipeline_runs USING btree (stage, started_at DESC);


CREATE TABLE public.pipeline_errors (
    id bigint NOT NULL,
    run_id text NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    -- The step within the run ('scrape', 'extract', 'write', …), not the stage.
    step text NOT NULL,
    thinker text,
    error_class text,
    error_message text,
    traceback text,
    retry_attempted boolean DEFAULT false NOT NULL,
    outcome text,
    detail jsonb
);

ALTER TABLE public.pipeline_errors ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pipeline_errors_id_seq
    START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
);

ALTER TABLE ONLY public.pipeline_errors ADD CONSTRAINT pipeline_errors_pkey PRIMARY KEY (id);

-- No FK to pipeline_runs: an error must be recordable even if the run row was
-- never written (or was pruned first). Losing the error is the worse outcome.
CREATE INDEX idx_pipeline_errors_run ON public.pipeline_errors USING btree (run_id, occurred_at);
CREATE INDEX idx_pipeline_errors_occurred ON public.pipeline_errors USING btree (occurred_at DESC);


-- Stale documents. `documents` is keyed output; only 'map' has a reader.
--   'keynote'   — the keynote generator was removed; nothing has read this
--                 since, and it is ~72 KB of jsonb per environment.
--   'synthesis' — a projection of fields the map document already carries, so
--                 the frontend never fetched it. Its writer is gone too.
-- Application data, so this is deliberately not reversed on the way down: the
-- generators that produced these rows no longer exist to recreate them.
DELETE FROM public.documents WHERE key IN ('keynote', 'synthesis');

-- migrate:down

DROP TABLE IF EXISTS public.pipeline_errors;
DROP TABLE IF EXISTS public.pipeline_runs;
